package com.healthcare.activitytracker.config;

import java.util.Arrays;
import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Component;

/**
 * Fails startup in the {@code prod} profile when a secret is unfit to be one, and warns about it
 * everywhere else.
 *
 * <p>Covers every secret the application derives a key from — the two JWT signing secrets and the
 * passphrase that encrypts stored Google OAuth tokens at rest — and rejects three ways they go
 * wrong: a value that ships in this repository, access and refresh secrets that are identical, and
 * a secret long enough to satisfy the algorithm but made of padding.
 */
@Component
public class StartupSecretValidator implements ApplicationRunner {

  private static final Logger log = LoggerFactory.getLogger(StartupSecretValidator.class);

  private static final Set<String> INSECURE_DEFAULTS =
      Set.of(
          "default-dev-secret-key-change-in-production-must-be-at-least-32-chars",
          "default-dev-refresh-secret-change-in-production-at-least-32-chars");

  /** Below this, a secret is padding rather than something generated. See validateSecretVariety. */
  private static final int MIN_DISTINCT_CHARACTERS = 12;

  private final String jwtSecret;
  private final String jwtRefreshSecret;
  private final GoogleHealthProperties googleHealthProperties;
  private final Environment environment;

  public StartupSecretValidator(
      @Value("${app.jwt.secret}") String jwtSecret,
      @Value("${app.jwt.refresh-secret}") String jwtRefreshSecret,
      GoogleHealthProperties googleHealthProperties,
      Environment environment) {
    this.jwtSecret = jwtSecret;
    this.jwtRefreshSecret = jwtRefreshSecret;
    this.googleHealthProperties = googleHealthProperties;
    this.environment = environment;
  }

  @Override
  public void run(ApplicationArguments args) {
    boolean isProduction = Arrays.asList(environment.getActiveProfiles()).contains("prod");
    boolean hasInsecureSecret = INSECURE_DEFAULTS.contains(jwtSecret);
    boolean hasInsecureRefresh = INSECURE_DEFAULTS.contains(jwtRefreshSecret);

    if (hasInsecureSecret || hasInsecureRefresh) {
      String message =
          "JWT secrets are set to insecure default values. "
              + "Set JWT_SECRET and JWT_REFRESH_SECRET environment variables.";
      failOrWarn(isProduction, message);
    }

    // Identical secrets collapse the access/refresh key separation: a refresh token would
    // carry a valid signature under the access key (only the type claim would stop it).
    if (jwtSecret.equals(jwtRefreshSecret)) {
      failOrWarn(
          isProduction,
          "JWT_SECRET and JWT_REFRESH_SECRET are identical. Access and refresh tokens must be "
              + "signed with different keys.");
    }

    validateSecretVariety(isProduction, "JWT_SECRET", jwtSecret);
    validateSecretVariety(isProduction, "JWT_REFRESH_SECRET", jwtRefreshSecret);

    validateGoogleHealthTokenKey(isProduction);
  }

  /**
   * Rejects obviously degenerate secrets. {@code Keys.hmacShaKeyFor} already enforces 256 bits of
   * <em>length</em>, so a secret can be long enough for the algorithm and still be something like a
   * single repeated character.
   *
   * <p>Counting distinct characters is a smoke test, not a measure of entropy: it catches padded
   * placeholders without pretending to judge a real secret's strength. Anything generated by a
   * password manager or {@code openssl rand} clears it comfortably.
   */
  private void validateSecretVariety(boolean isProduction, String name, String secret) {
    long distinctCharacters = secret.chars().distinct().count();
    if (distinctCharacters < MIN_DISTINCT_CHARACTERS) {
      failOrWarn(
          isProduction,
          String.format(
              "%s contains only %d distinct characters, which means it is padding rather than a "
                  + "generated secret. Use a random value, e.g. openssl rand -base64 48.",
              name, distinctCharacters));
    }
  }

  /**
   * The Google OAuth token-encryption passphrase only matters when the integration is switched on —
   * with {@code enabled=false} nothing is ever encrypted with it, so the shipped default stays
   * harmless and must not block startup.
   */
  private void validateGoogleHealthTokenKey(boolean isProduction) {
    if (!googleHealthProperties.isEnabled()) {
      return;
    }
    if (GoogleHealthProperties.DEFAULT_TOKEN_ENCRYPTION_KEY.equals(
        googleHealthProperties.getTokenEncryptionKey())) {
      failOrWarn(
          isProduction,
          "The Google Health integration is enabled but its token-encryption key is still the "
              + "default that ships in this repository, so stored OAuth tokens are effectively "
              + "unencrypted. Set GOOGLE_HEALTH_TOKEN_KEY.");
    }
  }

  private void failOrWarn(boolean isProduction, String message) {
    if (isProduction) {
      throw new IllegalStateException(
          "FATAL: " + message + " Application cannot start in 'prod' profile.");
    }
    log.warn("WARNING: {} This is acceptable for local development only.", message);
  }
}
